nums = list(map(int,input("Enter the numbers:").split()))
nums.sort()
print("second largest number is:",nums[-2])
#len()
#max()
#min()
#sum()
#nums.sort()
#nums.append()
#nums.pop()
#nums.remove()
#set()
#range()